postgram 2/news/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from .views import index, about, create, good, POSTLoginView, profile, POSTLogoutView, ChangeUserInfoView, \
    POSTChangeView, RegisterUserView, RegisterDoneView, user_activate, DeleteUserView, editpost, deletepost, detail

app_name = 'news'

urlpatterns = [
    path('', index, name='index'),
    path('<int:pk>/', detail, name='detail'),
    path('accounts/profile/add/', create, name='add'),
    path('good/', good, name='good'),
    path('about/', about, name='about'),
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/login/', POSTLoginView.as_view(), name='login'),
    path('accounts/logout/', POSTLogoutView.as_view(), name='logout'),
    path('accounts/profile/delete', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/change', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/editpost/<int:pk>/', editpost, name='edit_post'),
    path('accounts/profile/deletepost/<int:pk>/', deletepost, name='delete_post'),
    path('accounts/password/change', POSTChangeView.as_view(), name='password_change'),

]

postgram 2/postgram/urls.py
from django.contrib import admin
from django.conf import settings 
from django.urls import path, include 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('news.urls',namespace='')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postgram 2/news/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import Signal
from .utilities import send_activation_notification
import os


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True,
                                       verbose_name='Прошел активацию?')
    avatar = models.ImageField(null=True, blank=True, upload_to="image/profile/")

    class Meta(AbstractUser.Meta):
        pass


class Post(models.Model):
    content = models.TextField(null=True, blank=False)
    image = models.ImageField(upload_to='image/%Y/%m/%d/', blank=True, null=True)
    file = models.FileField(upload_to='files/%Y/%m/%d/', blank=True, null=True)
    video = models.FileField(upload_to='video/%Y/%m/%d/', blank=True, null=True)
    audio = models.FileField(upload_to='audio/%Y/%m/%d/', blank=True, null=True)
    author = models.ForeignKey(AdvUser, on_delete=models.CASCADE, null=True)
    pubdate = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Publication date')

    class Meta:
        verbose_name_plural = 'Posts'
        verbose_name = 'Post'
        ordering = ['-pubdate']

    def filename(self):
        return os.path.basename(self.file.name)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    content = models.TextField(null=True, blank=False)
    author = models.CharField(max_length=30)
    pubdate = models.DateTimeField(auto_now_add=True, db_index=True)
    image = models.ImageField(upload_to='image/%Y/%m/%d/', blank=True, null=True)
    file = models.FileField(upload_to='files/%Y/%m/%d/', blank=True, null=True)
    video = models.FileField(upload_to='video/%Y/%m/%d/', blank=True, null=True)
    audio = models.FileField(upload_to='audio/%Y/%m/%d/', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Comments'
        verbose_name = 'Comment'
        ordering = ['-pubdate']


user_registrated = Signal(['instance'])


def user_registrated_dispatcher(sender, **kwargs):
    send_activation_notification(kwargs['instance'])


user_registrated.connect(user_registrated_dispatcher)

postgram 2/news/forms.py
from django.forms import ModelForm
from django import forms
from .models import Post, AdvUser, user_registrated, Comment
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        widgets = {'author': forms.HiddenInput}


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        widgets = {'post': forms.HiddenInput, 'author': forms.HiddenInput}


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Email')

    class Meta:
        model = AdvUser
        fields = ('username', 'avatar', 'email', 'first_name', 'last_name')


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Email')
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Password(repeat)', widget=forms.PasswordInput,
                                help_text='Repeat password')

    def clean_passwird1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Passwords do not match',
                                                   code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'avatar', 'email', 'password1', 'password2',
                  'first_name', 'last_name')

postgram 2/news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, AdvUser, Comment
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from .forms import PostForm, ChangeUserInfoForm, RegisterUserForm, CommentForm
from django.contrib.auth import logout
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordChangeView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.signing import BadSignature
from .utilities import signer


@login_required
def index(request):
    posts = Post.objects.all()
    return render(request, 'news/index.html', {'posts': posts})

    initial = {'post': post.pk}
    initial['author'] = request.user.username
    form_class = CommentForm
    form = form_class(initial=initial)
    if request.method == 'POST':
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save()
        else:
            form = c_form
    return render(request, 'news/index.html', {'post': post, 'comments': comments, 'form': form})


@login_required
def profile(request):
    posts = Post.objects.filter(author=request.user.pk)
    context = {'posts': posts}
    return render(request, 'news/profile.html', context)


@login_required
def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=pk)
    initial = {'post': post.pk}
    initial['author'] = request.user.username
    form_class = CommentForm
    form = form_class(initial=initial)
    if request.method == 'POST' or request.FILES:
        c_form = form_class(request.POST, request.FILES)
        if c_form.is_valid():
            c_form.save()
        else:
            form = c_form
    return render(request, 'news/detail.html', {'post': post, 'comments': comments, 'form': form})


@login_required
def create(request):
    if request.method == 'POST' or request.FILES:
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            return redirect('news:profile')
    else:
        form = PostForm(initial={'author': request.user.pk})
    context = {'form': form}
    return render(request, 'news/create.html', context)


@login_required
def editpost(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST' or request.FILES:
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            return redirect('news:profile')
    else:
        form = PostForm(instance=post)
    context = {'form': form}
    return render(request, 'news/editpost.html', context)


@login_required
def deletepost(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('news:profile')
    else:
        context = {'post': post}
    return render(request, 'news/deletepost.html', context)


@login_required
def good(request):
    return render(request, 'news/good.html')


@login_required
def about(request):
    return render(request, 'news/about.html')


class POSTLoginView(LoginView):
    template_name = 'news/login.html'


class POSTLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'news/logout.html'


class POSTChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'news/password_change.html'
    success_url = reverse_lazy('news:profile')
    success_message = 'Password changed'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'news/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('news:profile')
    success_message = 'Info changed'

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'news/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('news:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'news/register_done.html'


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'news/delete_user.html'
    success_url = reverse_lazy('news:index')

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'User deleted')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'news/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'news/user_is_activated.html'
    else:
        template = 'news/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)

postgram 2/news/templates/news/about.html
{% extends "layout/basic.html" %}

{% block title %}About{% endblock %}

{% block content %}
<div class="good">
	<img src="/static/news/IMG20220824204730.JPG" width="300px">
		Hello! My full name is Novogencev Pavel. I’m from Belarus, Gomel. I’m in my late teens. Currently I’m a student at F. Skorina Gomel State University. I’m studying to get a BSc in physics with a focus on radioelectronics. I chose this department because I like math and physics. I spend most of my time developing my skills in physics, programming and higher mathematics in order to become a highly-qualified specialist in this field. I’m looking for a job in IT company or anything related to that. I’m Adaptive and open to changes, motivated to learn more and to succeed, creative, hard-working, punctual, ambitious, well-organized, multitasking, a good team-player, planner. In the near future I want to graduate with good grades, get a well-paid job in a profitable company. As I have a multi-skilled specialty, I’m sure that my skills can be applied in various fields.<br>
		Contacts<br>
		<div class='soc-a'>
			<a href="https://vk.com/novogencev"><img src="/static/news/vk.png" class="soc"></a>
			<a href="https://www.instagram.com/novogencev/?hl=ru"><img  src="/static/news/insta.png" class="soc"></a>
			<a href="https://discordapp.com/users/524191442965495841/"><img src="/static/news/Discord-Logo-Color.png" class="soc"></a>
			<a href="https://www.linkedin.com/in/pavel-novozhentsev-bb8227220/"><img  src="/static/news/LI-In-Bug.png" class="soc"></a>
			<a href="https://t.me/joscraw"><img  src="/static/news/Logo.png" class="soc"></a>
		</div>
</div>
{% endblock %}

postgram 2/news/templates/news/activation_done.html
{% extends "layout/basic.html" %}


{% block title %}Activation done{% endblock %}

{% block content %}
	<h2>Activations</h2>
	<p>Successfully activated</p>
	<p><a href="{% url 'news:login' %}">Log in</a></p>
{% endblock %}

postgram 2/news/templates/news/bad_signature.html
{% extends "layout/basic.html" %}


{% block title %}Error{% endblock %}

{% block content %}
<div class="good">
	Activation unsuccessful<br>
	<a href="{% url 'news:register' %}" class="link">Register again</a>
</div>
{% endblock %}

postgram 2/news/templates/news/delete_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Deleting a user{% endblock %}

{% block content %}
<div class="good">
	Deleting a user {{object.username}}
	<form method="post">
		{% csrf_token %}
		<button type="submit">Delete</button>
	</form>
</div>
{% endblock %}

postgram 2/news/templates/news/deletepost.html
{% extends "layout/basic.html" %}

{% block title %}Delete post{% endblock %}
{% block content %}
<div class="good">
	Delete post
	<div class="post">
		<div class="post-author">
			<div class="post-author-a">
				{% if post.author.avatar %}
			      <img class="avatar-small" src="{{ post.author.avatar.url }}">
			    {% else %}
			      <img class="avatar-small" src="\static\news\user.png">
			    {% endif %}
			    <div>
					{{ post.author }}<br>
					{{ post.pubdate|date:"d M Y H:i" }}
				</div>
			</div>
		</div>
		<div class="post-content">
			{{ post.content}}<br>
			{% if post.image %}
				<img src="{{ post.image.url }}" class="media">
			{% endif %}
			{% if post.video %}
				<video src="{{ post.video.url }}" class="media" controls="controls"></video><br>
			{% endif %}
			{% if post.audio %}
				<audio src="{{ post.audio.url }}" controls="controls"></audio><br>
			{% endif %}
			{% if post.file %}
				<a href='{{ post.file.url }}' target="-blank" class="file">{{post.filename}}</a><br>
			{% endif %}
		</div>
	</div>
	<form method="post">
	    {% csrf_token %}
	    <button type="submit">Delete</button>
	</form>
</div>
{% endblock %}

postgram 2/news/templates/news/detail.html
{% extends "layout/basic.html" %}

{% block content %}
<div class="good">
	<div class="post">
		<div class="post-author">
			<div class="post-author-a">
				{% if post.author.avatar %}
			      <img class="avatar-small" src="{{ post.author.avatar.url }}">
			    {% else %}
			      <img class="avatar-small" src="\static\news\user.png">
			    {% endif %}
				<div>
					{{ post.author }}<br>
					{{ post.pubdate|date:"d M Y H:i" }}
				</div>
			</div>
		</div>
		<div class="post-content">
			{{ post.content}}<br>
			{% if post.image %}
				<a href="{{ post.image.url }}"><img src="{{ post.image.url }}" class="media"></a>
			{% endif %}
			{% if post.video %}
				<video src="{{ post.video.url }}" class="media" controls="controls"></video><br>
			{% endif %}
			{% if post.audio %}
				<audio src="{{ post.audio.url }}" controls="controls"></audio><br>
			{% endif %}
			{% if post.file %}
				<a href='{{ post.file.url }}' target="-blank" class="file">{{post.filename}}</a><br>
			{% endif %}
		</div>
	</div>
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Add comment</button>
		</form><br>
		{% if comments %}
			{% for comment in comments %}
			<div class="comment">
				{{ comment.author }} {{ comment.pubdate|date:"d M Y H:i" }}<br>
				{{ comment.content|urlize }}<br>
			</div>
			{% endfor %}
		{% endif %}
</div>
{% endblock %}

postgram 2/news/templates/news/editpost.html
{% extends "layout/basic.html" %}

{% block title %}Edit post{% endblock %}
{% block content %}
<div class="good">
	Edit post
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Edit</button>
	</form>
</div>
{% endblock %}

postgram 2/news/templates/news/good.html
{% extends "layout/basic.html" %}

{% block title %}Useful links{% endblock %}

{% block content %}
<div class="good">
	Useful links:<br>
		<a href="http://old.gsu.by/physfac/" class="link">⚫Сайт факультета физики и ИТ</a><br>
		<a href="https://www.desmos.com/calculator?lang=ru" class="link">⚫Графический калькулятор</a><br>
		<a href="https://drive.google.com/drive/folders/1AXYmwLO0JELWV_2GlSurWkARgirbNK7m?usp=sharing" class="link">⚫Видео ЛР КМ (2 курс, 2 семестр)</a>
</div>
{% endblock %}

postgram 2/news/templates/news/index.html
{% extends "layout/basic.html" %}

{% block content %}
{% if user.is_authenticated %}
{% if posts %}
{% for post in posts %}
	<div class="post">
		<div class="post-author">
			<div class="post-author-a">
				{% if post.author.avatar %}
			      <img class="avatar-small" src="{{ post.author.avatar.url }}">
			    {% else %}
			      <img class="avatar-small" src="\static\news\user.png">
			    {% endif %}
			    <div>
					{{ post.author }}<br>
					{{ post.pubdate|date:"d M Y H:i" }}
				</div>
			</div>
			<div class="post-author-b">
				<a href="{% url 'news:detail' pk=post.pk %}" class="link">⋮</a>
			</div>
		</div>
		<div class="post-content">
			{{ post.content}}<br>
			{% if post.image %}
				<a href="{{ post.image.url }}"><img src="{{ post.image.url }}" class="media"></a>
			{% endif %}
			{% if post.video %}
				<video src="{{ post.video.url }}" class="media" controls="controls"></video><br>
			{% endif %}
			{% if post.audio %}
				<audio src="{{ post.audio.url }}" controls="controls"></audio><br>
			{% endif %}
			{% if post.file %}
				<a href='{{ post.file.url }}' target="-blank" class="file">{{post.filename}}</a><br>
			{% endif %}
		</div>
	</div>
{% endfor %}
{% endif %}
{% endif %}
{% endblock %}

postgram 2/news/templates/news/login.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="login">
	{% if user.is_authenticated%}
	Login already done
	{% else %}
	<form method="post">
		{% csrf_token %}
		{% bootstrap_form form layout='horizontal' %}
		<input type="hidden" name="next" value="{% url 'news:index' %}">
		{% buttons submit='Log in' %}{% endbuttons %}
	</form>
	{% endif %}
</div>
{% endblock %}

postgram 2/news/templates/news/logout.html
{% extends "layout/basic.html" %}


{% block titke %}Выход{% endblock %}

{% block content %}
	<h2>Выход</h2>
	<p>Вы вышли с аккаунта</p>
{% endblock %}

postgram 2/news/templates/news/profile.html
{% extends "layout/basic.html" %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="profile">
	Profile {{user.username }}
	{% if user.avatar %}
      <img class="avatar" src="{{ user.avatar.url }}"><br><br>
    {% else %}
      <img class="avatar" src="\static\news\user.png"><br><br>
    {% endif %}
	Hello, {{user.first_name}} {{user.last_name}}
	<div>
		<a href="{% url 'news:add' %}"  class="link">Add post</a>
		<a href="{% url 'news:profile_change' %}"  class="link">Edit info</a>
		<a href="{% url 'news:password_change' %}"  class="link">Edit password</a>
		<a href="{% url 'news:profile_delete' %}"  class="link">Delete</a>
	</div>
	Your post
</div>
<div>
	{% for post in posts %}
	<div class="post">
		<div class="post-author">
			<div class="post-author-a">
				{% if post.author.avatar %}
			      <img class="avatar-small" src="{{ post.author.avatar.url }}">
			    {% else %}
			      <img class="avatar-small" src="\static\news\user.png">
			    {% endif %}
			    <div>
					{{ post.author }}<br>
					{{ post.pubdate|date:"d M Y H:i" }}
				</div>
			</div>
			<div class="post-author-b">
				<a href="{% url 'news:detail' pk=post.pk %}" class="link">⋮</a>
			</div>
		</div>
		<div class="post-content">
			{{ post.content}}<br>
			{% if post.image %}
				<a href="{{ post.image.url }}"><img src="{{ post.image.url }}" class="media"></a>
			{% endif %}
			{% if post.video %}
				<video src="{{ post.video.url }}" class="media" controls="controls"></video><br>
			{% endif %}
			{% if post.audio %}
				<audio src="{{ post.audio.url }}" controls="controls"></audio><br>
			{% endif %}
			{% if post.file %}
				<a href='{{ post.file.url }}' target="-blank" class="file">{{post.filename}}</a><br>
			{% endif %}
			<br>
			<a href="{% url 'news:edit_post' pk=post.pk %}" class="link">Edit</a>
			<a href="{% url 'news:delete_post' pk=post.pk %}"  class="link">Delete</a>
		</div>
	</div>
{% endfor %}       
</div>
{% endblock %}

postgram 2/news/templates/news/register_done.html
{% extends "layout/basic.html" %}


{% block title %}Registration completed{% endblock %}

{% block content %}
<div class="good">
	An email has been sent to the email address provided with further instructions
</div>
{% endblock %}

postgram 2/news/templates/news/register_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Registration{% endblock %}

{% block content %}
<div class="good">
	Registration
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Register</button>
	</form>
</div>
{% endblock %}